// Каталог сочетаний клавиш для macOS и Windows.
// combo: { mac: 'Cmd+C', win: 'Ctrl+C' } — отображаемая комбинация.
// os: ['mac'] / ['win'] — сочетание перехватывается системой, поэтому оно
//      есть в учебнике, но исключено из тренажёра.
// opens: необязательно — что именно открывает сочетание.

export const CATEGORIES = [
  { id: 'general', icon: '📋', title: { ru: 'Основные', en: 'General' } },
  { id: 'text', icon: '✍️', title: { ru: 'Работа с текстом', en: 'Text editing' } },
  { id: 'browser', icon: '🌐', title: { ru: 'Браузер', en: 'Browser' } },
  { id: 'files', icon: '📁', title: { ru: 'Файлы', en: 'Files' } },
  { id: 'useful', icon: '🚀', title: { ru: 'Полезные штуки', en: 'Useful things' } },
  { id: 'windows', icon: '🪟', title: { ru: 'Окна и приложения', en: 'Windows & apps' } },
  { id: 'my', icon: '⭐', title: { ru: 'Мои сочетания', en: 'My shortcuts' } }
];

export const SHORTCUTS = [
  // ── Основные ─────────────────────────────────────────────
  { id: 'copy', cat: 'general', combo: { mac: 'Cmd+C', win: 'Ctrl+C' },
    title: { ru: 'Копировать', en: 'Copy' },
    desc: { ru: 'Копирует выделенный текст или файл в буфер обмена.', en: 'Copies the selected text or file to the clipboard.' } },
  { id: 'cut', cat: 'general', combo: { mac: 'Cmd+X', win: 'Ctrl+X' },
    title: { ru: 'Вырезать', en: 'Cut' },
    desc: { ru: 'Перемещает выделенное в буфер обмена.', en: 'Moves the selection to the clipboard.' } },
  { id: 'paste', cat: 'general', combo: { mac: 'Cmd+V', win: 'Ctrl+V' },
    title: { ru: 'Вставить', en: 'Paste' },
    desc: { ru: 'Вставляет содержимое буфера обмена.', en: 'Pastes the clipboard contents.' } },
  { id: 'paste-special', cat: 'general', combo: { mac: 'Cmd+Opt+Shift+V', win: 'Ctrl+Shift+V' },
    title: { ru: 'Вставить без форматирования', en: 'Paste as plain text' },
    desc: { ru: 'Вставляет текст без стилей и оформления.', en: 'Pastes text without any styling.' } },
  { id: 'undo', cat: 'general', combo: { mac: 'Cmd+Z', win: 'Ctrl+Z' },
    title: { ru: 'Отменить', en: 'Undo' },
    desc: { ru: 'Отменяет последнее действие.', en: 'Undoes the last action.' } },
  { id: 'redo', cat: 'general', combo: { mac: 'Cmd+Shift+Z', win: 'Ctrl+Y' },
    title: { ru: 'Повторить', en: 'Redo' },
    desc: { ru: 'Возвращает отменённое действие.', en: 'Redoes the undone action.' } },
  { id: 'select-all', cat: 'general', combo: { mac: 'Cmd+A', win: 'Ctrl+A' },
    title: { ru: 'Выделить всё', en: 'Select all' },
    desc: { ru: 'Выделяет всё содержимое.', en: 'Selects everything.' } },
  { id: 'find', cat: 'general', combo: { mac: 'Cmd+F', win: 'Ctrl+F' },
    title: { ru: 'Найти', en: 'Find' },
    desc: { ru: 'Открывает поиск по документу или странице.', en: 'Opens find-in-page.' } },
  { id: 'find-next', cat: 'general', combo: { mac: 'Cmd+G', win: 'Ctrl+G' },
    title: { ru: 'Следующий результат поиска', en: 'Next search result' },
    desc: { ru: 'Переходит к следующему совпадению.', en: 'Jumps to the next match.' } },
  { id: 'save', cat: 'general', combo: { mac: 'Cmd+S', win: 'Ctrl+S' },
    title: { ru: 'Сохранить', en: 'Save' },
    desc: { ru: 'Сохраняет текущий файл.', en: 'Saves the current file.' } },
  { id: 'print', cat: 'general', combo: { mac: 'Cmd+P', win: 'Ctrl+P' },
    title: { ru: 'Печать', en: 'Print' },
    desc: { ru: 'Открывает окно печати.', en: 'Opens the print dialog.' } },

  // ── Текст ────────────────────────────────────────────────
  { id: 'bold', cat: 'text', combo: { mac: 'Cmd+B', win: 'Ctrl+B' },
    title: { ru: 'Жирный', en: 'Bold' },
    desc: { ru: 'Делает выделенный текст жирным.', en: 'Makes the selected text bold.' } },
  { id: 'italic', cat: 'text', combo: { mac: 'Cmd+I', win: 'Ctrl+I' },
    title: { ru: 'Курсив', en: 'Italic' },
    desc: { ru: 'Наклоняет выделенный текст.', en: 'Italicizes the selected text.' } },
  { id: 'underline', cat: 'text', combo: { mac: 'Cmd+U', win: 'Ctrl+U' },
    title: { ru: 'Подчёркнутый', en: 'Underline' },
    desc: { ru: 'Подчёркивает выделенный текст.', en: 'Underlines the selected text.' } },
  { id: 'word-left', cat: 'text', combo: { mac: 'Opt+Left', win: 'Ctrl+Left' },
    title: { ru: 'К началу слова', en: 'Start of word' },
    desc: { ru: 'Перемещает курсор к началу слова.', en: 'Moves the cursor to the start of the word.' } },
  { id: 'line-start', cat: 'text', combo: { mac: 'Cmd+Left', win: 'Home' },
    title: { ru: 'К началу строки', en: 'Start of line' },
    desc: { ru: 'Перемещает курсор в начало строки.', en: 'Moves the cursor to the beginning of the line.' } },
  { id: 'line-end', cat: 'text', combo: { mac: 'Cmd+Right', win: 'End' },
    title: { ru: 'К концу строки', en: 'End of line' },
    desc: { ru: 'Перемещает курсор в конец строки.', en: 'Moves the cursor to the end of the line.' } },
  { id: 'delete-word', cat: 'text', combo: { mac: 'Opt+Backspace', win: 'Ctrl+Backspace' },
    title: { ru: 'Удалить слово', en: 'Delete word' },
    desc: { ru: 'Удаляет слово слева от курсора.', en: 'Deletes the word to the left of the cursor.' } },
  { id: 'select-word', cat: 'text', combo: { mac: 'Opt+Shift+Right', win: 'Ctrl+Shift+Right' },
    title: { ru: 'Выделить слово', en: 'Select word' },
    desc: { ru: 'Выделяет слово справа от курсора.', en: 'Selects the word to the right.' } },
  { id: 'emoji', cat: 'text', combo: { mac: 'Ctrl+Cmd+Space', win: 'Win+.' },
    title: { ru: 'Эмодзи', en: 'Emoji' },
    desc: { ru: 'Открывает панель эмодзи.', en: 'Opens the emoji picker.' },
    os: ['mac', 'win'] },

  // ── Браузер ──────────────────────────────────────────────
  { id: 'new-tab', cat: 'browser', combo: { mac: 'Cmd+T', win: 'Ctrl+T' },
    title: { ru: 'Новая вкладка', en: 'New tab' },
    desc: { ru: 'Открывает новую вкладку.', en: 'Opens a new tab.' } },
  { id: 'close-tab', cat: 'browser', combo: { mac: 'Cmd+W', win: 'Ctrl+W' },
    title: { ru: 'Закрыть вкладку', en: 'Close tab' },
    desc: { ru: 'Закрывает текущую вкладку или окно.', en: 'Closes the current tab or window.' } },
  { id: 'reopen-tab', cat: 'browser', combo: { mac: 'Cmd+Shift+T', win: 'Ctrl+Shift+T' },
    title: { ru: 'Вернуть закрытую вкладку', en: 'Reopen closed tab' },
    desc: { ru: 'Восстанавливает только что закрытую вкладку.', en: 'Reopens the tab you just closed.' } },
  { id: 'next-tab', cat: 'browser', combo: { mac: 'Ctrl+Tab', win: 'Ctrl+Tab' },
    title: { ru: 'Следующая вкладка', en: 'Next tab' },
    desc: { ru: 'Переключает на следующую вкладку.', en: 'Switches to the next tab.' } },
  { id: 'reload', cat: 'browser', combo: { mac: 'Cmd+R', win: 'Ctrl+R' },
    title: { ru: 'Обновить страницу', en: 'Reload page' },
    desc: { ru: 'Перезагружает страницу.', en: 'Reloads the page.' } },
  { id: 'address-bar', cat: 'browser', combo: { mac: 'Cmd+L', win: 'Ctrl+L' },
    title: { ru: 'Адресная строка', en: 'Address bar' },
    desc: { ru: 'Выделяет адрес страницы.', en: 'Focuses the address bar.' } },
  { id: 'back', cat: 'browser', combo: { mac: 'Cmd+[', win: 'Alt+Left' },
    title: { ru: 'Назад', en: 'Back' },
    desc: { ru: 'Возвращает на предыдущую страницу.', en: 'Goes back to the previous page.' } },
  { id: 'forward', cat: 'browser', combo: { mac: 'Cmd+]', win: 'Alt+Right' },
    title: { ru: 'Вперёд', en: 'Forward' },
    desc: { ru: 'Переходит вперёд по истории.', en: 'Goes forward in history.' } },
  { id: 'history', cat: 'browser', combo: { mac: 'Cmd+Y', win: 'Ctrl+H' },
    title: { ru: 'История', en: 'History' },
    desc: { ru: 'Открывает историю просмотров.', en: 'Opens browsing history.' } },
  { id: 'bookmark', cat: 'browser', combo: { mac: 'Cmd+D', win: 'Ctrl+D' },
    title: { ru: 'В закладки', en: 'Bookmark' },
    desc: { ru: 'Добавляет страницу в закладки.', en: 'Adds the page to bookmarks.' } },
  { id: 'private', cat: 'browser', combo: { mac: 'Cmd+Shift+N', win: 'Ctrl+Shift+N' },
    title: { ru: 'Приватное окно', en: 'Private window' },
    desc: { ru: 'Открывает окно в приватном режиме.', en: 'Opens a private/incognito window.' } },
  { id: 'downloads', cat: 'browser', combo: { mac: 'Cmd+Shift+J', win: 'Ctrl+J' },
    title: { ru: 'Загрузки', en: 'Downloads' },
    desc: { ru: 'Открывает список загрузок.', en: 'Opens the downloads list.' } },

  // ── Файлы ────────────────────────────────────────────────
  { id: 'new-folder', cat: 'files', combo: { mac: 'Cmd+Shift+N', win: 'Ctrl+Shift+N' },
    title: { ru: 'Новая папка', en: 'New folder' },
    desc: { ru: 'Создаёт новую папку.', en: 'Creates a new folder.' } },
  { id: 'rename', cat: 'files', combo: { mac: 'Enter', win: 'F2' },
    title: { ru: 'Переименовать', en: 'Rename' },
    desc: { ru: 'Переименовывает выбранный файл или папку.', en: 'Renames the selected file or folder.' } },
  { id: 'open-item', cat: 'files', combo: { mac: 'Cmd+O', win: 'Enter' },
    title: { ru: 'Открыть', en: 'Open' },
    desc: { ru: 'Открывает выбранный файл или папку.', en: 'Opens the selected file or folder.' } },
  { id: 'delete-file', cat: 'files', combo: { mac: 'Cmd+Delete', win: 'Delete' },
    title: { ru: 'Удалить', en: 'Delete' },
    desc: { ru: 'Удаляет файл (на Mac — сразу в корзину).', en: 'Deletes the file (straight to Trash on Mac).' } },
  { id: 'quick-look', cat: 'files', combo: { mac: 'Space', win: 'Alt+Enter' },
    title: { ru: 'Быстрый просмотр / свойства', en: 'Quick look / properties' },
    desc: { ru: 'На Mac — быстрый просмотр файла, в Windows — свойства.', en: 'Quick preview on Mac, file properties on Windows.' } },
  { id: 'duplicate', cat: 'files', combo: { mac: 'Cmd+D', win: 'Ctrl+D' },
    title: { ru: 'Дублировать', en: 'Duplicate' },
    desc: { ru: 'Создаёт копию файла или папки.', en: 'Duplicates a file or folder.' } },
  { id: 'props', cat: 'files', combo: { mac: 'Cmd+I', win: 'Alt+Enter' },
    title: { ru: 'Свойства файла', en: 'File properties' },
    desc: { ru: 'Открывает свойства файла или папки.', en: 'Opens file or folder properties.' } },
  { id: 'go-up', cat: 'files', combo: { mac: 'Cmd+[', win: 'Alt+Up' },
    title: { ru: 'На уровень выше', en: 'Go up' },
    desc: { ru: 'Открывает родительскую папку.', en: 'Opens the parent folder.' } },

  // ── Полезные штуки ───────────────────────────────────────
  { id: 'spotlight', cat: 'useful', combo: { mac: 'Cmd+Space' },
    title: { ru: 'Spotlight — поиск всего', en: 'Spotlight — search everything' },
    desc: { ru: 'Мгновенный поиск приложений, файлов и веб-страниц.', en: 'Instant search for apps, files and web pages.' },
    opens: { ru: 'Открывает: поиск Spotlight', en: 'Opens: Spotlight search' },
    os: ['mac'] },
  { id: 'win-search', cat: 'useful', combo: { win: 'Win+S' },
    title: { ru: 'Поиск в Windows', en: 'Windows search' },
    desc: { ru: 'Поиск приложений, файлов и настроек в Windows.', en: 'Search for apps, files and settings in Windows.' },
    opens: { ru: 'Открывает: панель поиска Windows', en: 'Opens: Windows search pane' },
    os: ['win'] },
  { id: 'run', cat: 'useful', combo: { win: 'Win+R' },
    title: { ru: 'Выполнить…', en: 'Run…' },
    desc: { ru: 'Запуск программ по имени или команде.', en: 'Run a program by name or command.' },
    opens: { ru: 'Открывает: окно «Выполнить»', en: 'Opens: the Run dialog' },
    os: ['win'] },
  { id: 'explorer-mac', cat: 'useful', combo: { mac: 'Cmd+Opt+L' },
    title: { ru: 'Открыть загрузки в Finder', en: 'Open Downloads in Finder' },
    desc: { ru: 'Быстро открывает папку «Загрузки».', en: 'Quickly opens the Downloads folder.' },
    opens: { ru: 'Открывает: Finder, папка «Загрузки»', en: 'Opens: Finder, Downloads folder' } },
  { id: 'explorer-win', cat: 'useful', combo: { win: 'Win+E' },
    title: { ru: 'Открыть проводник', en: 'Open File Explorer' },
    desc: { ru: 'Запускает проводник файлов.', en: 'Launches File Explorer.' },
    opens: { ru: 'Открывает: проводник Windows', en: 'Opens: Windows File Explorer' },
    os: ['win'] },
  { id: 'task-manager', cat: 'useful', combo: { mac: 'Cmd+Opt+Esc', win: 'Ctrl+Shift+Esc' },
    title: { ru: 'Принудительное завершение', en: 'Force quit' },
    desc: { ru: 'Завершает зависшее приложение.', en: 'Force-quits an unresponsive app.' },
    opens: { ru: 'Открывает: диспетчер задач', en: 'Opens: task manager' },
    os: ['mac', 'win'] },
  { id: 'settings-win', cat: 'useful', combo: { win: 'Win+I' },
    title: { ru: 'Настройки Windows', en: 'Windows Settings' },
    desc: { ru: 'Открывает системные настройки.', en: 'Opens system settings.' },
    opens: { ru: 'Открывает: параметры Windows', en: 'Opens: Windows Settings' },
    os: ['win'] },
  { id: 'settings-mac', cat: 'useful', combo: { mac: 'Cmd+,' },
    title: { ru: 'Настройки приложения', en: 'App settings' },
    desc: { ru: 'Открывает настройки текущего приложения.', en: 'Opens the current app’s settings.' } },
  { id: 'screenshot-area', cat: 'useful', combo: { mac: 'Cmd+Shift+4', win: 'Win+Shift+S' },
    title: { ru: 'Снимок области', en: 'Screenshot area' },
    desc: { ru: 'Делает скриншот выделенной области.', en: 'Takes a screenshot of a selected area.' },
    opens: { ru: 'Открывает: инструмент скриншота', en: 'Opens: screenshot tool' },
    os: ['mac', 'win'] },
  { id: 'clipboard', cat: 'useful', combo: { win: 'Win+V' },
    title: { ru: 'История буфера обмена', en: 'Clipboard history' },
    desc: { ru: 'Показывает ранее скопированные фрагменты.', en: 'Shows previously copied items.' },
    opens: { ru: 'Открывает: история буфера обмена', en: 'Opens: clipboard history' },
    os: ['win'] },
  { id: 'lock', cat: 'useful', combo: { mac: 'Ctrl+Cmd+Q', win: 'Win+L' },
    title: { ru: 'Заблокировать экран', en: 'Lock screen' },
    desc: { ru: 'Мгновенно блокирует компьютер.', en: 'Instantly locks the computer.' },
    os: ['mac', 'win'] },
  { id: 'recording', cat: 'useful', combo: { mac: 'Cmd+Shift+5', win: 'Win+Alt+R' },
    title: { ru: 'Запись экрана', en: 'Screen recording' },
    desc: { ru: 'Записывает видео с экрана.', en: 'Records video of the screen.' },
    opens: { ru: 'Открывает: запись экрана', en: 'Opens: screen recording' },
    os: ['mac', 'win'] },

  // ── Окна и приложения ────────────────────────────────────
  { id: 'switch-app', cat: 'windows', combo: { mac: 'Cmd+Tab', win: 'Alt+Tab' },
    title: { ru: 'Переключение приложений', en: 'Switch apps' },
    desc: { ru: 'Переключается между открытыми программами.', en: 'Switches between open programs.' },
    os: ['mac', 'win'] },
  { id: 'minimize', cat: 'windows', combo: { mac: 'Cmd+M', win: 'Win+Down' },
    title: { ru: 'Свернуть окно', en: 'Minimize window' },
    desc: { ru: 'Сворачивает окно на панель задач.', en: 'Minimizes the window.' },
    os: ['win'] },
  { id: 'fullscreen', cat: 'windows', combo: { mac: 'Ctrl+Cmd+F', win: 'Win+Up' },
    title: { ru: 'Во весь экран', en: 'Fullscreen' },
    desc: { ru: 'Разворачивает окно на весь экран.', en: 'Maximizes the window to fullscreen.' },
    os: ['win'] },
  { id: 'app-windows', cat: 'windows', combo: { mac: 'Cmd+`' },
    title: { ru: 'Окна этого приложения', en: 'Windows of this app' },
    desc: { ru: 'Переключает между окнами одной программы.', en: 'Switches between windows of one app.' } },
  { id: 'snap-left', cat: 'windows', combo: { win: 'Win+Left' },
    title: { ru: 'Прикрепить окно слева', en: 'Snap window left' },
    desc: { ru: 'Прикрепляет окно к левой половине экрана.', en: 'Snaps the window to the left half of the screen.' },
    os: ['win'] },
  { id: 'mission', cat: 'windows', combo: { mac: 'Ctrl+Up', win: 'Win+Tab' },
    title: { ru: 'Обзор окон', en: 'Task view' },
    desc: { ru: 'Показывает все открытые окна.', en: 'Shows all open windows.' },
    os: ['mac', 'win'] },
  { id: 'desktop', cat: 'windows', combo: { mac: 'Cmd+F3', win: 'Win+D' },
    title: { ru: 'Показать рабочий стол', en: 'Show desktop' },
    desc: { ru: 'Сворачивает все окна.', en: 'Minimizes all windows.' },
    os: ['mac', 'win'] }
];

// Проверка: доступно ли сочетание на данной платформе.
export function availableOn(shortcut, platform) {
  return Boolean(shortcut.combo && shortcut.combo[platform]);
}

// Комбинация для платформы.
export function comboFor(shortcut, platform) {
  return shortcut.combo ? shortcut.combo[platform] : null;
}

// Перехватывается ли сочетание системой (не подходит для тренажёра).
export function isOsLevel(shortcut, platform) {
  return Boolean(shortcut.os && shortcut.os.includes(platform));
}
